using System;
using System.Drawing;
using System.Collections.Generic;
using System.Text;
using System.Numerics;

namespace Ez.Windowing
{
    /// <summary>
    /// Defines the event data for the <see cref="IWindow.MouseDown"/>, 
    /// <see cref="IWindow.MouseEntered"/>, <see cref="IWindow.MouseLeft"/>,
    /// <see cref="IWindow.MouseMove"/>, <see cref="IWindow.MouseRepeat"/>,
    /// <see cref="IWindow.MouseUp"/>, or <see cref="IWindow.MouseWheel"/>.
    /// </summary>
    public struct MouseEventArgs
    {
        /// <summary>
        /// If the event was generated by any <see cref="MouseButton"/>,
        /// contains the button that generated the event, otherwise 
        /// <see cref="MouseButton.None"/>.
        /// </summary>
        public MouseButton Button { get; }

        /// <summary>
        /// If the event was generated by any <see cref="MouseButton"/>, 
        /// contain the type of event generated by the button, otherwise
        /// <see cref="KeyEvent.None"/>.
        /// </summary>
        public KeyEvent KeyEvent { get; }

        /// <summary>
        /// The number of times a mouse button was <see cref="KeyEvent.Down"/> and 
        /// <see cref="KeyEvent.Up"/>.
        /// </summary>
        public byte Clicks { get; }

        /// <summary>
        /// Gets the scroll offset along the x and y axis.
        /// </summary>
        public Vector2 Delta { get; }

        /// <summary>
        /// Gets the location of the mouse during the event.
        /// </summary>
        public Vector2 Location { get; }

        /// <summary>
        /// Gets the x-coordinate of the mouse during the generating mouse event.
        /// </summary>
        public float X => Location.X;

        /// <summary>
        /// Gets the y-coordinate of the mouse during the generating mouse event.
        /// </summary>
        public float Y => Location.Y;

        /// <summary>
        /// Initializes a new instance of the <see cref="MouseEventArgs"/> class.
        /// </summary>
        /// <param name="button">The mouse button that generate the event.</param>
        /// <param name="clicks">The number of times a mouse button was 
        /// <see cref="KeyEvent.Down"/> and <see cref="KeyEvent.Up"/>.</param>
        /// <param name="delta">The scroll offset along the x and y axis.</param>
        /// <param name="location">The location of the mouse during the event.</param>
        /// <param name="keyEvent">The key event that generate the event.</param>
        public MouseEventArgs(
            in MouseButton button, 
            in byte clicks, 
            in Vector2 delta,
            in Vector2 location, 
            in KeyEvent keyEvent)
        {
            (Button, Clicks, Delta, Location, KeyEvent) = 
                (button, clicks, delta, location, keyEvent);
        }
    }
}
